// GENERATED by scripts/build-dojo-stories.mjs — do not edit by hand.
//
// Per-story content hash (sha256 over the encoded mp4 + poster webp), used to
// bust caches when prerendered media is replaced under the same public path.
// Next serves static images as `immutable` in production, so a replaced file
// at an unchanged URL would keep showing stale covers for up to a year.
//
// Regenerate with: pnpm stories:build

export const DOJO_STORIES_MEDIA_VERSIONS = {
  "story-01": "58999131",
  "story-02": "782ddf15",
  "story-03": "df098b77",
  "story-04": "200e3819",
  "story-05": "a2d15051",
  "story-06": "0ada73f9",
  "story-07": "2c7cf4bf",
} as const
